# Generated by Django 4.0.dev20210410182312 on 2021-04-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('publishedDatetime', models.DateTimeField(auto_now_add=True)),
                ('idEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrys.entry')),
            ],
            options={
                'ordering': ['publishedDatetime'],
            },
        ),
    ]
