# Generated by Django 4.0.dev20210410182312 on 2021-04-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='idEntry',
            new_name='entryId',
        ),
    ]
