# Generated by Django 4.0.dev20210410182312 on 2021-04-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0003_rename_identry_comment_entryid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-publishedDatetime']},
        ),
    ]
