# Generated by Django 4.0.dev20210410182312 on 2021-04-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0005_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(),
        ),
    ]
